[package]
name = "order-processor"
edition.workspace = true
license.workspace = true
version.workspace = true
publish = false

[dependencies]
axum.workspace = true
my-infra-otel = { path = "../../crates/my-infra-otel" }
reqwest.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "time"] }
tracing.workspace = true
